version: '3.8'

services:
  ethereum-node:
    build:
      context: .
      network: host
    networks:
      - bridge
    image: ghcr.io/xorde-labs/docker-ethereum-node:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8545 || exit 1" ]
      interval: 10s
      timeout: 10s
    volumes:
      - ethereum_data:/home/ethereum/.ethereum
      - shared_data:/home/ethereum/.shared
    ports:
      - ${P2P_PORT}:30303/tcp
    environment:
      - P2P_MAX_PEERS
      - P2P_DISCOVERY_DISABLE
      - RPC_ENABLE
      - RPC_HOST
      - RPC_MODULES
      - RPC_ALLOW_UNPROTECTEDTX
      - RPC_WS_HOST
      - RPC_WS_MODULES
      - RPC_JWT_PATH
      - RPC_AUTH_ADDR
      - RPC_AUTH_PORT
      - RPC_AUTH_VHOSTS
      - NETWORK
      - SYNCMODE
      - NOPRUNING_ENABLE
      - DB_CACHE

  beacon-node:
    networks:
      - bridge
    depends_on:
      - ethereum-node
    image: sigp/lighthouse:latest
    restart: unless-stopped
    volumes:
      - beacon_data:/root/.lighthouse
      - shared_data:/.shared
    ports:
      - ${BEACON_PORT}:9000/tcp
      - ${BEACON_PORT}:9000/udp
    entrypoint: ['lighthouse', 'bn']
    command: [
      '--network', 'mainnet',
      '--http',
      '--execution-endpoint', 'http://ethereum-node:8551',
      '--execution-jwt', '/.shared/rpc/jwtsecret',
      '--checkpoint-sync-url', 'https://mainnet.checkpoint.sigp.io',
      ### remove if you are staking:
      '--disable-deposit-contract-sync',
    ]

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - ${RPC_PORT}:80
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/default.conf

volumes:
  ethereum_data:
    driver: local
  beacon_data:
    driver: local
  shared_data:
    driver: local

networks:
  bridge:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
### check MTU: cat /sys/class/net/eth0/mtu

